Added facet limit - Changed customizer show more button layout
Weble/YOOalgolia pull request #1
Opened 2022-03-31 10:51 UTC by daveewbl

2022-03-31 15:11 UTC, Skullbock requested changes

2022-03-31 15:11 UTC, Skullbock commented on plugin/builder/algolia_facet/element.json
> +                        "limit",
per convenzione, metti un underscore al campo "limit", così tutti i campi che non hanno un valore ma sono solo estetici, come questo "group", non "occupano" chiavi valore utili.

2022-03-31 15:11 UTC, Skullbock commented on plugin/builder/algolia_facet/templates/template.php
> +        limit="<?= $props['limit'] ?>"
Credo che qui quindi sia "show_more_limit". "Limit" è il nome del campo gruppo.

2022-04-11 10:37 UTC, daveewbl commented on plugin/builder/algolia_facet/element.json
> +                        "limit",
Capito, però "limit" in realtà ha un valore, è il limite di facets stampati senza lo "show more" (di default da libreria 10). Per questo ho raggruppato le proprietà del pulsante e lasciato fuori "limit"

2022-04-11 10:39 UTC, merged